//! Bounded, non-authoritative claim decisions for peer index bootstrap.

use super::transfer::{TransferEffect, TransferEvent};
use crate::{NodeId, Time};

/// Stable application scope for one index image and origin builder.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BootstrapScope {
    /// Source/application domain, such as an origin endpoint identity.
    pub domain: String,
    /// Partition within that domain, such as an S3 bucket.
    pub partition: String,
}

impl BootstrapScope {
    /// Collision-free rendezvous key: the byte length delimits the domain.
    #[must_use]
    pub fn placement_key(&self) -> String {
        format!("{}:{}{}", self.domain.len(), self.domain, self.partition)
    }
}

/// Fixed resource and logical-time limits for one scope.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BootstrapConfig {
    /// Maximum complete member/claim roster entries.
    pub max_members: usize,
    /// Maximum UTF-8 bytes in one member ID.
    pub max_member_bytes: usize,
    /// Maximum combined UTF-8 bytes in the scope names.
    pub max_scope_bytes: usize,
    /// Time allowed for claims to converge before selecting a builder.
    pub settle_ms: u64,
    /// Local cadence for publishing a fresh, monotone renewal sequence.
    pub renew_ms: u64,
    /// Native TTL for an advertised claim.
    pub claim_ttl_ms: u64,
    /// Finite observation attempt timeout.
    pub observe_ms: u64,
    /// Finite wait for a selected builder or donor.
    pub donor_wait_ms: u64,
    /// Total budget for this bootstrap selection episode.
    pub total_ms: u64,
}

impl BootstrapConfig {
    /// Rejects absent, inverted, or unbounded limits.
    ///
    /// # Errors
    /// Returns [`BootstrapError::InvalidConfig`] for an invalid bound.
    pub fn validate(self) -> Result<Self, BootstrapError> {
        if self.max_members == 0
            || self.max_members == usize::MAX
            || self.max_member_bytes == 0
            || self.max_scope_bytes == 0
            || self.settle_ms == 0
            || self.renew_ms == 0
            || self.claim_ttl_ms <= self.renew_ms
            || self.observe_ms == 0
            || self.donor_wait_ms == 0
            || self.total_ms == 0
            || self.settle_ms >= self.total_ms
            || self.observe_ms > self.total_ms
            || self.donor_wait_ms > self.total_ms
        {
            return Err(BootstrapError::InvalidConfig);
        }
        Ok(self)
    }
}

/// Caller-supplied boot nonce, fresh across process restarts for one node.
///
/// The core does not generate entropy. A runtime must obtain 128 bits from an
/// operating-system CSPRNG or a documented operator-backed monotonic identity.
/// Tests may inject fixed nonzero values.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct BootId(pub u128);

/// One session/attempt identity; a reboot must supply a fresh incarnation.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct ClaimIdentity {
    /// Member identity used by Groupnet placement.
    pub node: NodeId,
    /// Caller-supplied, nonzero boot identity, never generated by this core.
    pub incarnation: BootId,
    /// Fresh nonzero session identity within this process/boot.
    pub session: u64,
    /// Monotone local attempt within that boot.
    pub attempt: u64,
}

/// Claim state is a donor availability hint, never a read-authority proof.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum ClaimPhase {
    /// Eligible for deterministic builder selection.
    Willing,
    /// Origin build selected and in progress.
    Building,
    /// Builder reports an image candidate available for guarded transfer.
    Ready,
}

/// One native TTL entry observed through a bounded source snapshot.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BootstrapClaim {
    /// Exact node, boot, session, and attempt.
    pub identity: ClaimIdentity,
    /// Strictly increasing on each renewal of this exact claim.
    pub renewal: u64,
    /// Candidate's advertised phase.
    pub phase: ClaimPhase,
    /// Native source TTL remaining at the observation, not a fresh local TTL.
    pub remaining_ms: u64,
}

/// One complete-roster member eligibility fact.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BootstrapMember {
    /// Native Groupnet node identity.
    pub node: NodeId,
    /// Whether this member is currently eligible to build or donate.
    pub eligible: bool,
}

/// Correlation for one core operation, from a single checked allocator.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BootstrapOperation {
    /// Local session identity.
    pub session: u64,
    /// Caller-supplied fresh boot identity; protects token reuse after restart.
    pub incarnation: BootId,
    /// Supersession generation.
    pub generation: u64,
    /// Unique token within the session.
    pub token: u64,
}

/// Non-authoritative selection phase.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BootstrapStage {
    /// No claim has been published.
    Unready,
    /// Publishing and allowing a connected claim set to converge.
    Settling,
    /// Reading a bounded current roster and claim set.
    Observing,
    /// This node is the provisional origin builder.
    Building,
    /// Following a selected builder or ready donor.
    Following,
    /// A candidate image may be requested, but no read permission is granted.
    DonorAvailable,
    /// A bounded donor transfer is active under the original selected claim.
    Transferring,
    /// Private candidate installed; external read and lease gates still apply.
    Transferred,
    /// Selection budget ended; the ordinary origin fallback remains available.
    Fallback,
    /// Terminal local cancellation.
    Cancelled,
}

/// Fail-closed input or state rejection.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BootstrapError {
    /// Constructor or scope limits are invalid.
    InvalidConfig,
    /// Input belongs to the wrong phase.
    Stage,
    /// Callback does not match the current operation or selected claim.
    StaleOperation,
    /// Source supplied incomplete, over-limit, or contradictory facts.
    InvalidObservation,
    /// Time moved backward.
    BackwardTime,
    /// Checked generation, token, renewal, or logical-time arithmetic ended.
    Exhausted,
}

/// Explicit observation, completion, failure, and clock inputs.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum BootstrapEvent {
    /// Publish a fresh local claim and start one finite selection episode.
    Start,
    /// One source-certified complete bounded member and claim snapshot.
    ClaimsObserved {
        /// Exact observation operation.
        op: BootstrapOperation,
        /// All members in scope, bounded before adapter allocation.
        members: Vec<BootstrapMember>,
        /// All source TTL claims in scope, bounded before adapter allocation.
        claims: Vec<BootstrapClaim>,
    },
    /// Local guarded origin build completed; image still needs transfer proof.
    Built {
        /// Exact build operation.
        op: BootstrapOperation,
        /// Exact selected local builder identity.
        selected: ClaimIdentity,
    },
    /// Local guarded origin build failed or lost its recovery permit.
    BuildFailed {
        /// Exact build operation.
        op: BootstrapOperation,
        /// Exact selected local builder identity.
        selected: ClaimIdentity,
    },
    /// Exact selected donor became unavailable, with callback correlation.
    DonorUnavailable {
        /// Exact follow operation.
        op: BootstrapOperation,
        /// Selected node, boot, and attempt the callback observed.
        selected: ClaimIdentity,
    },
    /// Fresh native TTL observation of the exact selected claim during transfer.
    SelectedClaimObserved {
        /// Exact refresh operation from the same session allocator.
        op: BootstrapOperation,
        /// Absent means the donor claim is no longer source-visible.
        claim: Option<BootstrapClaim>,
    },
    /// Begin the opt-in transfer for this exact selected ready donor.
    StartTransfer {
        /// Original follow operation retained as the transfer parent.
        op: BootstrapOperation,
        /// Exact selected donor identity.
        selected: ClaimIdentity,
    },
    /// One exact event for the bounded transfer child.
    Transfer(Box<TransferEvent>),
    /// Monotone caller-supplied logical time.
    Tick(Time),
    /// Withdraw the local claim and end this session.
    Cancel,
}

/// Bounded work for an external source/runtime adapter.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum BootstrapEffect {
    /// Cancel/fence exactly this old work before any replacement image work.
    CancelWork {
        /// Correlated work being superseded.
        op: BootstrapOperation,
    },
    /// Publish/renew the exact claim with native TTL and new renewal sequence.
    PublishClaim(BootstrapClaim),
    /// Best-effort withdrawal; stale entries must still expire by native TTL.
    WithdrawClaim(ClaimIdentity),
    /// Read a complete roster and claims through a pre-allocation bounded API.
    ObserveClaims {
        /// Exact observation operation.
        op: BootstrapOperation,
        /// Pre-allocation cap for the complete member and claim roster.
        max_members: usize,
        /// Pre-allocation cap for each member identity.
        max_member_bytes: usize,
    },
    /// Begin the existing guarded origin recovery as provisional builder.
    BuildOrigin {
        /// Exact build operation.
        op: BootstrapOperation,
        /// Exact provisional builder identity.
        selected: ClaimIdentity,
    },
    /// Await a selected builder's candidate without opening local reads.
    FollowBuilder {
        /// Exact follow operation.
        op: BootstrapOperation,
        /// Exact candidate identity.
        selected: ClaimIdentity,
    },
    /// A ready donor can be tried for a separate bounded transfer session.
    DonorAvailable {
        /// Exact follow operation.
        op: BootstrapOperation,
        /// Exact donor identity.
        selected: ClaimIdentity,
    },
    /// Refresh exact selected donor TTL without replacing the transfer parent.
    ObserveSelectedClaim {
        /// Exact refresh operation, separate from the parent and child work.
        op: BootstrapOperation,
        /// Exact donor identity to read from native TTL storage.
        selected: ClaimIdentity,
    },
    /// Work owned by the transfer child and the same session token allocator.
    Transfer(Box<TransferEffect>),
    /// Use the ordinary guarded origin recovery path after selection fails.
    FallbackOrigin,
    /// Earliest logical deadline across claim renewal and current work.
    ArmTimer(Time),
}

/// One deterministic transition result.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BootstrapStep {
    /// Bounded effects for the runtime to execute.
    pub effects: Vec<BootstrapEffect>,
    /// Rejection, when the event cannot be accepted.
    pub rejection: Option<BootstrapError>,
}
